export enum PaymentStatus {
  CREATED = 'CREATED',
  PENDING = 'PENDING',
  AUTHORIZED = 'AUTHORIZED',
  CAPTURED = 'CAPTURED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
  EXPIRED = 'EXPIRED'
}

export enum PaymentMethod {
  CARD = 'CARD',
  BANK_TRANSFER = 'BANK_TRANSFER',
  MOBILE_WALLET = 'MOBILE_WALLET',
  CASH = 'CASH',
  INSTALLMENTS = 'INSTALLMENTS'
}

export enum WebhookStatus {
  RECEIVED = 'RECEIVED',
  VALIDATED = 'VALIDATED',
  PROCESSED = 'PROCESSED',
  FAILED = 'FAILED',
  RETRIED = 'RETRIED',
  DEAD_LETTER = 'DEAD_LETTER'
}

export enum ProviderHealthStatus {
  HEALTHY = 'HEALTHY',
  DEGRADED = 'DEGRADED',
  DOWN = 'DOWN'
}

export enum PaymentProvider {
  PAYMOB = 'PAYMOB',
  STRIPE = 'STRIPE',
  PAYPAL = 'PAYPAL',
  MYFATOORAH = 'MYFATOORAH'
}
