export const ErrorCodeRegistry = {
  BAD_REQUEST: 'ERR_BAD_REQUEST',
  UNAUTHORIZED: 'ERR_UNAUTHORIZED',
  FORBIDDEN: 'ERR_FORBIDDEN',
  NOT_FOUND: 'ERR_NOT_FOUND',
  CONFLICT: 'ERR_CONFLICT',
  VALIDATION: 'ERR_VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR: 'ERR_INTERNAL_SERVER_ERROR',
  BUSINESS_RULE_VIOLATION: 'ERR_BUSINESS_RULE_VIOLATION',
};
