apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eduverse-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: api.eduverse.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: eduverse-api-service
            port:
              number: 80
