import { Injectable } from '@nestjs/common';
import { IAIProvider, IChatProvider, IEmbeddingProvider, IContentGenerationProvider, IVisionProvider, ITranscriptionProvider } from '../domain/ai-providers.interface';

@Injectable()
export class MockAiProviderService implements IAIProvider, IChatProvider, IEmbeddingProvider, IContentGenerationProvider, IVisionProvider, ITranscriptionProvider {
  getProviderName(): string {
    return 'MockAIProvider';
  }

  async generateText(prompt: string, options?: any): Promise<{ text: string; usage: { promptTokens: number; completionTokens: number } }> {
    return {
      text: `[Mock AI Response for prompt: "${prompt}"] Evaluated student data shows standard performance boundaries.`,
      usage: { promptTokens: 120, completionTokens: 45 },
    };
  }

  async sendMessage(sessionId: string, message: string): Promise<{ reply: string; usage: { promptTokens: number; completionTokens: number } }> {
    return {
      reply: `[Mock AI Tutor Chat] Hello, I received your message: "${message}". Let's work on this topic together!`,
      usage: { promptTokens: 150, completionTokens: 60 },
    };
  }

  async getEmbedding(text: string): Promise<number[]> {
    return Array.from({ length: 1536 }, () => Math.random());
  }

  async generateLessonContent(topic: string, gradeLevel: string): Promise<string> {
    return `<h1>Lesson: ${topic} (${gradeLevel})</h1><p>This lesson outline was automatically generated by EduVerse AI.</p>`;
  }

  async analyzeDocument(fileBuffer: Buffer, mimeType: string): Promise<string> {
    return '[Mock AI Vision analysis] Document is clear and verified. Found keywords: "Academic Report", "GPA: 3.8".';
  }

  async transcribeAudio(fileBuffer: Buffer): Promise<string> {
    return '[Mock AI Transcription] This is a mock transcription of the classroom lecture audio.';
  }
}
